name:                &#127993; Arc Reformas
title:               &#127993; Arc Reformas
url:                 https://www.arcreformas.com.br
enforce_ssl:         arcreformas.com.br
baseurl:             ""

permalink:           :slug
relative_permalinks: false

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
